### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#1]
## Value Statement

As a user, I want to know my options when I enter the app, so that I can navigate easily

## Description

![Screenshot 2021-04-26 at 12 03 21](https://user-images.githubusercontent.com/78050731/116065549-6b8b0200-a687-11eb-87ac-2c08d0e9ce5d.png)

## Acceptance Criteria

* The landing page contains links to the different paths 
* One nav button links to the products page
* The other links to the weekly routine page

## Tasks

- [x] Create feature branch
- [x] Link to product page
- [x] Link to routine page
- [x] Styling landing page

## Complexity
small
