### ISSUE TITLE
Create Filter component

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#13]
## Value Statement

As a user, I want to filter products, so I can find them more easily

## Acceptance Criteria

* Products need to appear in accordance with set filter
* User needs to be able to filter products by name and category

## Tasks

- [x] Create feature branch
- [x] Write filter logic for name filter
- [x] Write filter logic for category filter

## Complexity
medium
