### ISSUE TITLE
Create product list page

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#2]
## Value Statement

As a user, I want to view products, so that I can pick the ones I want in my routine

## Description

![Screenshot 2021-04-26 at 12 04 02](https://user-images.githubusercontent.com/78050731/116065637-8198c280-a687-11eb-9f3f-21a4bd8ca0c2.png)

## Acceptance Criteria

* Products need to be displayed with name, image, details and "add" option

## Tasks

- [x] Create feature branch
- [x] Create product card component
- [x] Create filter component
- [x] Render product data in component
- [x] Styling product card component and product list page

## Complexity
medium
