### ISSUE TITLE
Alert if products have conflicts

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#26]
## Value Statement

As a user, I don't want to use products together that have conflicts, so that I can maximize the benefits from my routine
## Acceptance Criteria

* User needs to be alerted about conflicts when trying to add two products that should not be used together
* Use should be asked whether or not they want to add the product anyway

## Tasks

- [x] Create feature branch
- [x] Write logic to check stored data to see if products have conflict (Check for conflicting idea)
- [x] Render name of the products that are conflicting

## Complexity
large
