### ISSUE TITLE
Add products to routine

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#3]
## Value Statement

As a user, I want to select products, so that I can add them to my weekly routine

## Description

![Screenshot 2021-04-26 at 12 05 22](https://user-images.githubusercontent.com/78050731/116065857-bc025f80-a687-11eb-9ce9-40ab18929e77.png)

## Acceptance Criteria

* Clicking the "+" button on the product card pops up a modal
* Modal asks user when they want to use the product (day and time of day)
* Clicking "add" on the modal component pushes the product to selected days and time of day

## Tasks

- [ ] Create feature branch
- [ ] Write event listener logic for "+" button on product card
- [ ] Create modal component
- [ ] Write event listener logic for "add" button on modal
- [ ] Send entered data to local storage
- [ ] Styling modal

## Complexity
large
