### ISSUE TITLE
Have checkboxes pre-checked

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#33]
## Value Statement

As a user, I want to know when I am already using the product when i click it in the product list, so that I don't have to manually check

## Acceptance Criteria

* When clicking an already added product, the check boxes should be checked on the days & times of day when the product has already been added

## Tasks

- [x] Create feature branch
- [x] Get data from localStorage
- [x] Change the checked property for days when product is already used according to LocalStorage

## Complexity
medium
