### ISSUE TITLE
Edit days on which product is added

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#34]
## Value Statement

As a user, I want to edit the product days, so that I can change my routine

## Acceptance Criteria

* When the user opens the FormModal they can select and deselect days & times of day
* Inside localStorage the object with the corresponding product id gets manipulated accordingly (set false for deselected days and true for selected days and update the date input in case there was a change

## Tasks

- [x] Get Object from localStorage that has corresponding id
- [x] Update object with new information
- [x] Add updated object to the array

## Complexity
large
