### ISSUE TITLE
Create weekly routine page

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#4]
## Value Statement

As a user, I want to view my weekly routine, so that I have an overview

## Description

![Screenshot 2021-04-26 at 12 06 54](https://user-images.githubusercontent.com/78050731/116066026-e5bb8680-a687-11eb-8acd-1dfc207528cb.png)

## Acceptance Criteria

* The "+" button takes the user to the product list page
* If products are already added, the page displays cards for every weekday with the routines for that day's morning and evening

## Tasks

- [x] Create feature branch
- [x] Create week day component
- [x] Get data from local storage to check if anything has been added and render data
- [x] Add navigation route for "+" button
- [x] Add styling

## Complexity
medium
