### ISSUE TITLE
Let user swap products

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#49]
## Value Statement

As a user, when I try to add a product to e.g. monday morning, that has conflicts with a product that is already added to monday morning, I want to be given the opportunity to swap the current product with the conflicting product in my routine., so that i don't have to go to the conflicting product to edit the times manually and then come back to the current to add it.

## Acceptance Criteria

* User needs to be alerted when trying to add conflicting products
* User needs to be given two buttons: cancel and swap
* Clicking swap will remove the conflicting product and add the current product instead

## Tasks

- [x] Create feature branch
- [x] Implement logic to remove conflicting product on "swap" clicked
- [x] Implement logic to send new current product info to LS

## Complexity
medium
