### ISSUE TITLE
Create daily routine page

### ISSUE THREAD

**Issue by FriederikeM** [FriederikeM/routinely#5]
## Value Statement

As a user, I want to view my daily routine routine, so that I can edit it and restock on product

## Description

![Screenshot 2021-04-26 at 12 23 43](https://user-images.githubusercontent.com/78050731/116068187-3fbd4b80-a68a-11eb-993d-981fec55fb5a.png)

## Acceptance Criteria

* Products need to be displayed including: image, name, expiration period, opening date, edit button and option to restock
* The edit button pops up the modal that asks the user when they want to use their product
* The modal should already contain the information the user has entered for this product
* The restock icon takes the user to the website that sells the product
* "back" button takes user back to weekly routine

## Tasks

- [x] Create feature branch
- [x] Create modified product component (use same one as for product list page, but with different props?)
- [x] Get data from local storage to display on pop up modal
- [x] Add navigation route for "back" button (useHistory)
- [x] Add styling

## Complexity
medium
